class Strings{

  List<String> suggestions = [
    "shoes",
    "clothing",
    "accessories",
    "electronics",
    "phones",
    "laptops",
    "home decor",
    "furniture",
    "beauty products",
    "health products",
    "toys",
    "sports equipment",
    "books",
    "video games",
    "pet supplies",
    "food and beverages",
    "jewelry",
    "watches",
    "outdoor gear",
    "camping equipment",
    "tools",
    "office supplies",
    "musical instruments",
    "art supplies",
    "party supplies",
    "baby products",
    "craft supplies",
    "gifts",
    "stationery",
    "car parts",
    "motorcycle parts",
    "bicycle parts",
    "photography equipment",
    "fitness equipment",
    "home appliances",
    "kitchen appliances",
    "bedding",
    "bath accessories",
    "cleaning supplies",
    "gardening supplies",

  ];

}